CREATE TABLE IF NOT EXISTS movies (
    `title` VARCHAR(37) CHARACTER SET utf8,
    `year` VARCHAR(6) CHARACTER SET utf8,
    `score` NUMERIC(3, 0),
    `url` VARCHAR(72) CHARACTER SET utf8
);
INSERT INTO movies VALUES
    ('Running Scared','(1986)',59,'https://www.rottentomatoes.com/m/1018009-running_scared'),
    ('Equilibrium','(2002)',41,'https://www.rottentomatoes.com/m/equilibrium'),
    ('Hero','(2002)',94,'https://www.rottentomatoes.com/m/hero'),
    ('Road House','(1989)',37,'https://www.rottentomatoes.com/m/1017666-road_house'),
    ('Unstoppable','(2010)',87,'https://www.rottentomatoes.com/m/unstoppable-2010'),
    ('Shaft','(1971)',86,'https://www.rottentomatoes.com/m/1018699-shaft'),
    ('The Villainess','(2017)',85,'https://www.rottentomatoes.com/m/the_villainess'),
    ('Highlander','(1986)',70,'https://www.rottentomatoes.com/m/highlander'),
    ('Die Hard 2','(1990)',69,'https://www.rottentomatoes.com/m/die_hard_2_1990'),
    ('National Treasure','(2004)',46,'https://www.rottentomatoes.com/m/national_treasure'),
    ('The Protector','(2005)',53,'https://www.rottentomatoes.com/m/protector'),
    ('Revenge','(2017)',93,'https://www.rottentomatoes.com/m/revenge_2018'),
    ('El Mariachi','(1992)',91,'https://www.rottentomatoes.com/m/el_mariachi'),
    ('A Touch of Zen','(1971)',97,'https://www.rottentomatoes.com/m/touch_of_zen'),
    ('Top Gun','(1986)',57,'https://www.rottentomatoes.com/m/top_gun'),
    ('Con Air','(1997)',55,'https://www.rottentomatoes.com/m/con_air'),
    ('The Expendables 2','(2012)',67,'https://www.rottentomatoes.com/m/the_expendables_2'),
    ('The Mummy','(1999)',61,'https://www.rottentomatoes.com/m/1087270-mummy'),
    ('Mr. & Mrs. Smith','(2005)',60,'https://www.rottentomatoes.com/m/mr_and_mrs_smith'),
    ('Rush Hour','(1998)',60,'https://www.rottentomatoes.com/m/rush_hour'),
    ('The Equalizer','(2014)',60,'https://www.rottentomatoes.com/m/the_equalizer_2013'),
    ('Captain America: Civil War','(2016)',90,'https://www.rottentomatoes.com/m/captain_america_civil_war'),
    ('Air Force One','(1997)',78,'https://www.rottentomatoes.com/m/air_force_one'),
    ('Bloodsport','(1988)',46,'https://www.rottentomatoes.com/m/bloodsport'),
    ('Blade','(1998)',57,'https://www.rottentomatoes.com/m/1083484-blade'),
    ('Bad Boys','(1995)',42,'https://www.rottentomatoes.com/m/1062483-bad_boys'),
    ('Die Hard With a Vengeance','(1995)',59,'https://www.rottentomatoes.com/m/die_hard_with_a_vengeance'),
    ('The Running Man','(1987)',66,'https://www.rottentomatoes.com/m/running_man'),
    ('Code of Silence','(1985)',70,'https://www.rottentomatoes.com/m/code_of_silence'),
    ('Shoot ''Em Up','(2007)',67,'https://www.rottentomatoes.com/m/shoot_em_up'),
    ('Crank','(2006)',61,'https://www.rottentomatoes.com/m/crank'),
    ('Machete','(2010)',72,'https://www.rottentomatoes.com/m/machete'),
    ('Drive','(2011)',93,'https://www.rottentomatoes.com/m/drive_2011'),
    ('Batman','(1989)',72,'https://www.rottentomatoes.com/m/1001781-batman'),
    ('Under Siege','(1992)',79,'https://www.rottentomatoes.com/m/under_siege'),
    ('Independence Day','(1996)',68,'https://www.rottentomatoes.com/m/1071806-independence_day'),
    ('Bullitt','(1968)',98,'https://www.rottentomatoes.com/m/bullitt'),
    ('Wanted','(2008)',71,'https://www.rottentomatoes.com/m/1174279-wanted'),
    ('Superman: The Movie','(1978)',94,'https://www.rottentomatoes.com/m/superman_the_movie'),
    ('Ronin','(1998)',69,'https://www.rottentomatoes.com/m/ronin'),
    ('They Live','(1988)',85,'https://www.rottentomatoes.com/m/they_live'),
    ('Cliffhanger','(1993)',67,'https://www.rottentomatoes.com/m/1044214-cliffhanger'),
    ('Marvel''s the Avengers','(2012)',91,'https://www.rottentomatoes.com/m/marvels_the_avengers'),
    ('Hot Fuzz','(2007)',91,'https://www.rottentomatoes.com/m/hot_fuzz'),
    ('The Warriors','(1979)',87,'https://www.rottentomatoes.com/m/1023205-warriors'),
    ('Starship Troopers','(1997)',66,'https://www.rottentomatoes.com/m/starship_troopers'),
    ('Elite Squad 2','(2010)',91,'https://www.rottentomatoes.com/m/elite_squad_the_enemy_within'),
    ('Point Break','(1991)',69,'https://www.rottentomatoes.com/m/point_break'),
    ('The Long Kiss Goodnight','(1996)',69,'https://www.rottentomatoes.com/m/long_kiss_goodnight'),
    ('The Guest','(2014)',92,'https://www.rottentomatoes.com/m/the_guest_2014'),
    ('Taken','(2008)',59,'https://www.rottentomatoes.com/m/taken'),
    ('300','(2006)',61,'https://www.rottentomatoes.com/m/300'),
    ('True Lies','(1994)',69,'https://www.rottentomatoes.com/m/true_lies'),
    ('Demolition Man','(1993)',62,'https://www.rottentomatoes.com/m/demolition_man'),
    ('Hardcore Henry','(2015)',51,'https://www.rottentomatoes.com/m/hardcore_henry'),
    ('Police Story','(1985)',93,'https://www.rottentomatoes.com/m/police_story'),
    ('Brotherhood of the Wolf','(2001)',73,'https://www.rottentomatoes.com/m/brotherhood_of_the_wolf'),
    ('Kingsman: The Secret Service','(2014)',75,'https://www.rottentomatoes.com/m/kingsman_the_secret_service'),
    ('The Fifth Element','(1997)',70,'https://www.rottentomatoes.com/m/fifth_element'),
    ('Big Trouble in Little China','(1986)',75,'https://www.rottentomatoes.com/m/big_trouble_in_little_china'),
    ('Atomic Blonde','(2017)',79,'https://www.rottentomatoes.com/m/atomic_blonde_2017'),
    ('Rumble in the Bronx','(1995)',80,'https://www.rottentomatoes.com/m/rumble_in_the_bronx'),
    ('District B13','(2004)',80,'https://www.rottentomatoes.com/m/district_b13'),
    ('Beverly Hills Cop','(1984)',83,'https://www.rottentomatoes.com/m/beverly_hills_cop'),
    ('Ong-Bak: The Thai Warrior','(2003)',85,'https://www.rottentomatoes.com/m/ongbak'),
    ('Collateral','(2004)',86,'https://www.rottentomatoes.com/m/collateral'),
    ('Iron Monkey','(1993)',91,'https://www.rottentomatoes.com/m/1075984-iron_monkey'),
    ('Escape From New York','(1981)',87,'https://www.rottentomatoes.com/m/1006717-escape_from_new_york'),
    ('Battle Royale','(2000)',88,'https://www.rottentomatoes.com/m/battle_royale'),
    ('Spider-Man 2','(2004)',93,'https://www.rottentomatoes.com/m/spiderman_2'),
    ('13 Assassins','(2010)',95,'https://www.rottentomatoes.com/m/13_assassins_2011'),
    ('Full Contact','(1992)',88,'https://www.rottentomatoes.com/m/full_contact'),
    ('Indiana Jones and the Last Crusade','(1989)',88,'https://www.rottentomatoes.com/m/indiana_jones_and_the_last_crusade'),
    ('Kung Fu Hustle','(2004)',90,'https://www.rottentomatoes.com/m/kung_fu_hustle'),
    ('A Better Tomorrow','(1986)',93,'https://www.rottentomatoes.com/m/better_tomorrow'),
    ('Iron Man','(2008)',94,'https://www.rottentomatoes.com/m/iron_man'),
    ('The Night Comes for Us','(2018)',91,'https://www.rottentomatoes.com/m/the_night_comes_for_us'),
    ('Logan','(2017)',94,'https://www.rottentomatoes.com/m/logan_2017'),
    ('Goldfinger','(1964)',99,'https://www.rottentomatoes.com/m/goldfinger'),
    ('Assault on Precinct 13','(1976)',95,'https://www.rottentomatoes.com/m/1001280-assault_on_precinct_13'),
    ('Wonder Woman','(2017)',93,'https://www.rottentomatoes.com/m/wonder_woman_2017'),
    ('The Chinese Connection','(1972)',83,'https://www.rottentomatoes.com/m/chinese_connection'),
    ('Captain America: The Winter Soldier','(2014)',90,'https://www.rottentomatoes.com/m/captain_america_the_winter_soldier_2014'),
    ('Oldboy','(2003)',81,'https://www.rottentomatoes.com/m/oldboy'),
    ('The French Connection','(1971)',97,'https://www.rottentomatoes.com/m/french_connection'),
    ('Furious 7','(2015)',82,'https://www.rottentomatoes.com/m/furious_7'),
    ('La Femme Nikita','(1990)',89,'https://www.rottentomatoes.com/m/la_femme_nikita'),
    ('Supercop','(1992)',96,'https://www.rottentomatoes.com/m/supercop'),
    ('Dirty Harry','(1971)',88,'https://www.rottentomatoes.com/m/dirty_harry'),
    ('Edge of Tomorrow','(2014)',91,'https://www.rottentomatoes.com/m/live_die_repeat_edge_of_tomorrow'),
    ('X2','(2003)',85,'https://www.rottentomatoes.com/m/x2_xmen_united'),
    ('The Fugitive','(1993)',96,'https://www.rottentomatoes.com/m/1046129-fugitive'),
    ('Black Panther','(2018)',96,'https://www.rottentomatoes.com/m/black_panther_2018'),
    ('Inception','(2010)',87,'https://www.rottentomatoes.com/m/inception'),
    ('Braveheart','(1995)',78,'https://www.rottentomatoes.com/m/1065684-braveheart'),
    ('Minority Report','(2002)',90,'https://www.rottentomatoes.com/m/minority_report'),
    ('Avengers: Endgame','(2019)',94,'https://www.rottentomatoes.com/m/avengers_endgame'),
    ('Dredd','(2012)',79,'https://www.rottentomatoes.com/m/dredd'),
    ('The Bourne Identity','(2002)',84,'https://www.rottentomatoes.com/m/bourne_identity'),
    ('Ip Man','(2008)',86,'https://www.rottentomatoes.com/m/ip_man'),
    ('Face/Off','(1997)',92,'https://www.rottentomatoes.com/m/faceoff'),
    ('To Live and Die in L.A.','(1985)',85,'https://www.rottentomatoes.com/m/to_live_and_die_in_la'),
    ('The Dark Knight','(2008)',94,'https://www.rottentomatoes.com/m/the_dark_knight'),
    ('Mission: Impossible -- Ghost Protocol','(2011)',93,'https://www.rottentomatoes.com/m/mission_impossible_ghost_protocol'),
    ('Fast Five','(2011)',77,'https://www.rottentomatoes.com/m/fast_five'),
    ('Lethal Weapon','(1987)',80,'https://www.rottentomatoes.com/m/lethal_weapon'),
    ('The Rock','(1996)',68,'https://www.rottentomatoes.com/m/1072011-rock'),
    ('RoboCop','(1987)',90,'https://www.rottentomatoes.com/m/1017712-robocop'),
    ('John Wick: Chapter 2','(2017)',89,'https://www.rottentomatoes.com/m/john_wick_chapter_2'),
    ('Casino Royale','(2006)',94,'https://www.rottentomatoes.com/m/casino_royale'),
    ('Baby Driver','(2017)',92,'https://www.rottentomatoes.com/m/baby_driver'),
    ('Fist of Legend','(1994)',100,'https://www.rottentomatoes.com/m/fist_of_legend'),
    ('The Killer','(1989)',98,'https://www.rottentomatoes.com/m/1032434-killer'),
    ('The Raid 2','(2014)',82,'https://www.rottentomatoes.com/m/the_raid_2'),
    ('Enter the Dragon','(1973)',95,'https://www.rottentomatoes.com/m/enter_the_dragon'),
    ('Commando','(1985)',69,'https://www.rottentomatoes.com/m/1004567-commando'),
    ('First Blood','(1982)',87,'https://www.rottentomatoes.com/m/first_blood'),
    ('Mission: Impossible Rogue Nation','(2015)',94,'https://www.rottentomatoes.com/m/mission_impossible_rogue_nation'),
    ('The Terminator','(1984)',100,'https://www.rottentomatoes.com/m/terminator'),
    (NULL,'()',NULL,'https:'),
    ('Kill Bill: Vol. 1','(2003)',85,'https://www.rottentomatoes.com/m/kill_bill_vol_1'),
    ('The Professional','(1994)',73,'https://www.rottentomatoes.com/m/leon_the_professional'),
    ('Speed','(1994)',94,'https://www.rottentomatoes.com/m/speed_1994'),
    ('Drunken Master II','(1994)',84,'https://www.rottentomatoes.com/m/legend_of_drunken_master'),
    ('John Wick','(2014)',86,'https://www.rottentomatoes.com/m/john_wick'),
    ('Crouching Tiger, Hidden Dragon','(2000)',97,'https://www.rottentomatoes.com/m/crouching_tiger_hidden_dragon'),
    ('Predator','(1987)',81,'https://www.rottentomatoes.com/m/predator'),
    ('The Bourne Ultimatum','(2007)',92,'https://www.rottentomatoes.com/m/bourne_ultimatum'),
    ('Total Recall','(1990)',82,'https://www.rottentomatoes.com/m/total_recall'),
    ('Mad Max 2','(1981)',94,'https://www.rottentomatoes.com/m/mad_max_2_the_road_warrior'),
    ('Heat','(1995)',87,'https://www.rottentomatoes.com/m/heat_1995'),
    ('The Raid: Redemption','(2011)',87,'https://www.rottentomatoes.com/m/the_raid_redemption'),
    ('Mission: Impossible -- Fallout','(2018)',97,'https://www.rottentomatoes.com/m/mission_impossible_fallout'),
    ('Raiders of the Lost Ark','(1981)',95,'https://www.rottentomatoes.com/m/raiders_of_the_lost_ark'),
    ('Aliens','(1986)',97,'https://www.rottentomatoes.com/m/1000617-aliens'),
    ('Hard-Boiled','(1992)',94,'https://www.rottentomatoes.com/m/hard_boiled'),
    ('The Matrix','(1999)',88,'https://www.rottentomatoes.com/m/matrix'),
    ('Terminator 2: Judgment Day','(1991)',93,'https://www.rottentomatoes.com/m/terminator_2_judgment_day'),
    ('Die Hard','(1988)',94,'https://www.rottentomatoes.com/m/die_hard'),
    ('Mad Max: Fury Road','(2015)',97,'https://www.rottentomatoes.com/m/mad_max_fury_road');
